import Link from "next/link";
import { AlertTriangle, FileText, CheckCircle2, ShieldAlert, ArrowLeft } from "lucide-react";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Terms of Service",
  description: "MindSense AI Terms of Service and Medical Disclaimer",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Header */}
      <header className="border-b border-white/10 bg-secondary/20 backdrop-blur-md sticky top-0 z-20">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
            <ArrowLeft size={16} /> Back to Home
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
              <span className="font-bold text-white text-xs">M</span>
            </div>
            <span className="font-bold text-white text-sm">MindSense AI</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-4xl mx-auto px-6 py-12 md:py-16">
        <div className="mb-10 text-center md:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs font-semibold mb-4">
            <FileText size={13} /> Legal Agreement & Guidelines
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-3">Terms of Service</h1>
          <p className="text-gray-400 text-sm">Effective Date: September 2026</p>
        </div>

        {/* PROMINENT MEDICAL & CRISIS DISCLAIMER CALLOUT BOX */}
        <div className="bg-red-500/10 border-2 border-red-500/40 rounded-2xl p-6 md:p-8 mb-10 text-red-200">
          <div className="flex items-center gap-3 mb-4">
            <AlertTriangle className="text-red-400 shrink-0" size={28} />
            <h3 className="text-lg md:text-xl font-bold text-red-300">
              MANDATORY MEDICAL & PSYCHIATRIC DISCLAIMER
            </h3>
          </div>
          <div className="space-y-3 text-sm leading-relaxed">
            <p>
              <strong>MINDSENSE AI IS NOT A LICENSED HEALTHCARE PROVIDER, MEDICAL CLINIC, OR PSYCHIATRIC FACILITY.</strong>
            </p>
            <p>
              MindSense AI is an artificial intelligence-powered software platform developed exclusively for emotional reflection, general supportive companionship, and wellness tracking. <strong>It does not provide medical diagnosis, clinical psychiatric evaluations, psychological treatment, therapy, or prescriptions.</strong>
            </p>
            <p>
              Interactions with MindSense AI do not establish a doctor-patient, therapist-client, or any other licensed healthcare professional relationship. The information, suggestions, or responses generated by MindSense AI are not intended to substitute for the professional judgment, advice, or care of a qualified physician or licensed mental health professional.
            </p>
            <div className="bg-red-950/60 border border-red-500/30 rounded-xl p-4 mt-4 text-xs font-semibold text-white">
              🚨 <strong>IMMEDIATE EMERGENCY:</strong> If you are feeling overwhelmed, having thoughts of harming yourself or others, or undergoing an acute medical emergency, please discontinue use of this application immediately and contact <strong>988</strong> (USA/Canada), <strong>112</strong> (EU/India), or <strong>Tele-MANAS at 14416 / 1800-891-4416</strong> (India), or proceed to the nearest hospital emergency room.
            </div>
          </div>
        </div>

        {/* Detailed Sections */}
        <div className="space-y-8 text-sm leading-relaxed text-gray-300">
          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <CheckCircle2 size={18} className="text-primary" /> 1. Acceptance of Terms
            </h2>
            <p>
              By accessing, browsing, registering for, or using the MindSense AI platform (including our web interface, API, or voice/video modalities), you confirm that you have read, understood, and agreed to be legally bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms in their entirety, you must not access or use the platform.
            </p>
          </section>

          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <ShieldAlert size={18} className="text-yellow-400" /> 2. Emergency Contact Authorization & Consent
            </h2>
            <p className="mb-2">
              MindSense AI includes an emergency SOS notification feature designed to alert designated contacts when severe emotional distress or imminent crisis indicators are detected during an active conversation.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Third-Party Consent:</strong> By designating any individual as an emergency contact, you warrant and represent that you have informed such individuals and received their explicit prior consent to receive automated emergency SMS notifications.
              </li>
              <li>
                <strong>No Guarantee of Delivery:</strong> While MindSense AI operates redundant messaging pipelines, SMS delivery depends on third-party telecommunications carriers and mobile hardware. MindSense AI does not guarantee delivery speeds or network availability.
              </li>
              <li>
                <strong>Auxiliary Safety:</strong> Emergency SOS notifications are an auxiliary safety mechanism and must never be relied upon as a primary lifeline in critical situations.
              </li>
            </ul>
          </section>

          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3">3. Eligibility and Account Security</h2>
            <p className="mb-2">
              You must be at least 18 years of age (or the age of majority in your jurisdiction) to create an account. You agree to:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Provide accurate, current, and complete registration information.</li>
              <li>Maintain the confidentiality of your credentials and immediate notification of unauthorized account access.</li>
              <li>Refrain from sharing account access credentials with third parties.</li>
            </ul>
          </section>

          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3">4. Acceptable Use Policy</h2>
            <p className="mb-2">You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the service for any illegal, harassing, defamatory, or abusive purpose.</li>
              <li>Attempt to reverse-engineer, decompile, probe, or breach the security boundaries of the API or database.</li>
              <li>Employ automated scrapers, flood scripts, or excessive requests designed to trigger denial-of-service conditions.</li>
              <li>Impersonate any person or entity, or falsify phone numbers or email addresses during registration.</li>
            </ul>
          </section>

          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3">5. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MINDSENSE AI, ITS CONTRIBUTORS, DEVELOPERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF LIFE, HEALTH COMPLICATIONS, EMOTIONAL DISTRESS, OR FAILURE OF EMERGENCY RESPONSE ARISING OUT OF OR IN CONNECTION WITH THE USE OR INABILITY TO USE THE PLATFORM. THE PLATFORM IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND.
            </p>
          </section>

          <section className="bg-secondary/20 border border-white/5 rounded-2xl p-6 md:p-8">
            <h2 className="text-lg font-bold text-white mb-3">6. Governing Law & Contact</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws. If you have questions regarding these terms, please contact us at <span className="text-primary font-mono">legal@mindsenseai.org</span>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
